spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunz1test
    username: yunz1
    password: Loona@0114
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  rest-template:
    connect-timeout: 300000  # ?? ????: 5? (300?)
    read-timeout: 300000     # ?? ????: 5? (300?)

server:
  port: 8000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

jwt:
  secret: your-very-secure-secret-key
  access-token-expiration: 3600000 # 1?? (ms)
  refresh-token-expiration: 604800000 # 7? (ms)